#!/usr/bin/env bash
# If available use the timeout command from coreutils to limit execution time to half an hour
pushd $(dirname $0) 2>&1 > /dev/null && BASEDIR=$(pwd) && popd 2>&1 > /dev/null
let TIMEOUT=600
TIMEOUTCMD=timeout
if type timeout 2>&1 > /dev/null; then
	TIMEOUTCMD="$TIMEOUTCMD $TIMEOUT"
else
	TIMEOUTCMD=""
fi
if $TIMEOUTCMD $(which python2.7) $0.py "$@"; then
	echo "$(date +"%Y-%m-%d %H:%M:%S") ${0##*/}[$$]: Finished." >> "/dev/stderr"
	[[ -r "${0}.hook.success" ]] && { echo "$(date +"%Y-%m-%d %H:%M:%S") ${0##*/}[$$]: Running hook script." >> "/dev/stderr"; source "${0}.hook.success"; }
	exit 0
else
	echo "$(date +"%Y-%m-%d %H:%M:%S") ${0##*/}[$$]: Finished with error status." >> "/dev/stderr"
	[[ -r "${0}.hook.failure" ]] && { echo "$(date +"%Y-%m-%d %H:%M:%S") ${0##*/}[$$]: Running hook script." >> "/dev/stderr" source "${0}.hook.failure"; }
	exit 1
fi
