#!/bin/bash
HOST=yggdrasil
DEVICES=$(echo $(mdadm --detail /dev/md0|grep -v /dev/md|grep -oE '/dev/.*$'|cut -c 1-8))
[[ "$HOST" == "$(hostname -s)" ]] || { echo "ERROR: this script is tailored to $HOST"; exit 1; }
read -p "Reinstall grub in ${DEVICES// /, }? (y/n) " ans
[[ "${ans:0:1}" == "y" ]] || { echo "Aborted. Byeeeeeeee ..."; exit 0; }
for i in $DEVICES; do
	echo "Embedding into $i"
	grub-install --no-floppy --recheck $i
done
