#!/bin/bash
# CRONTAB: 29   * *   *   *     /usr/bin/sudo /usr/local/bin/save-pkgstates
for tool in rm dirname readlink mkdir file dpkg apt-mark; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
LOCKFILE="${TMPDIR=/tmp}/${CURRABSPATH//\//_}${0##*/}.lock"
if ! (set -o noclobber; echo "$$" > "$LOCKFILE") 2> /dev/null; then
	echo -e "${cR}ERROR:${cZ} Lock failed, PID $(cat "$LOCKFILE") [$LOCKFILE]" >&2
	exit 1
fi
trap 'rm -f "$LOCKFILE"; trap - INT TERM EXIT; exit $?' INT TERM EXIT
BASEDIR="/etc/package-states.apt_and_dpkg"
DPKG="/usr/bin/dpkg"
APTMARK="/usr/bin/apt-mark"
EXTSTATES="/var/lib/apt/extended_states"
CP="/bin/cp"
[[ -d "$BASEDIR" ]] || mkdir "$BASEDIR" || { echo "ERROR ($0): failed to create $BASEDIR"; exit 1; }
DPKG_SELECTIONS="$BASEDIR/dpkg-selections.txt"
APT_AUTOMARKED="$BASEDIR/apt-marked-auto.txt"
APT_MANUALMARKED="$BASEDIR/apt-marked-manual.txt"
"$DPKG" --get-selections '*' > "$DPKG_SELECTIONS" || { echo "ERROR ($0): failed to save dpkg package selections"; exit 1; }
"$APTMARK" showauto > "$APT_AUTOMARKED" || { echo "ERROR ($0): failed to save automatic APT markers"; exit 1; }
"$APTMARK" showmanual > "$APT_MANUALMARKED" || { echo "ERROR ($0): failed to save manual APT markers"; exit 1; }
"$CP" "$EXTSTATES" "$BASEDIR/" || { echo "ERROR ($0): failed to save extended package states"; exit 1; }
