#!/bin/bash
[[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
grep -E '10.0.3.2' /etc/hosts|awk '{print $1 ":" $3}'|while read f; do
	IP=${f%%:*}
	NM=${f##*:}
	FN="/etc/lxc/guests/${NM}.conf"
	if [[ -f "$FN" ]]; then
		if ! grep -q $IP "$FN"; then
			echo "Didn't find $IP for $NM ... adjusting '$FN':"
			OLDIP=$(awk '$1 ~ /^lxc\.network\.ipv4$/ && $3 ~ /^10\./ {print $3}' "$FN")
			echo -e "\t${cR}<$OLDIP${cZ}"
			echo -e "\t${cG}>$IP${cZ}"
			cp -a "$FN" "${FN}.orig" && \
				awk '{ if ($1 ~ /^lxc\.network\.ipv4$/ && $3 ~ /^10\./) {$3 = "'$IP'"} print }' "${FN}.orig"|tee "$FN"|grep -E '^lxc\.network\.ipv4$'
		else
			echo "Matched $IP for $NM"
		fi
		rm -f "${FN}.orig"
	fi
done
