#!/bin/bash
[[ $UID -eq 0 ]] || { echo "ERROR: this script can only be run by root (e.g. use sudo)."; exit 1; }
# LVM volume group name under which the system volumes are stored
VGNAME="KVM_GUESTS"
# Where to mount the guest disks in the file system
MNTPFX="/mnt/kvm-guests"

function mount_single
{
	local vm="$1"
	local vmdisk="$2"

	echo -e "* Adding device mappings for: $vmdisk"
	kpartx -a "$vmdisk"
	blkid|grep '"ext4"'|grep "/dev/mapper/$VGNAME-$vm.img"|cut -d : -f 1|while read vmpart; do
		[[ -d "$MNTPFX/$vm" ]] || mkdir -p "$MNTPFX/$vm" || { echo "ERROR: Failed to create mount point folder $MNTPFX/$vm"; exit 1; }
		if mount|grep -q "^$vmpart"; then
			echo -en "\tWARNING: already mounted\n\t  "
			mount|grep "^$vmpart"
		else
			echo -e "\tMounting VM partition $vmpart on $MNTPFX/$vm"
			mount "$vmpart" "$MNTPFX/$vm"
		fi
	done
}

# Banner
if (($# > 0)); then
	for vm in "$@"; do
		lvdisplay|grep 'LV Name'|grep "/dev/$VGNAME/$vm.img"|awk '{print $3}'|while read vmdisk; do
			mount_single "$vm" "$vmdisk"
		done
	done
else
	echo "Scanning for system volumes and mounting all ..."
	lvdisplay|grep 'LV Name'|grep "/dev/$VGNAME/"|grep \.img|awk '{print $3}'|while read vmdisk; do
		vm=${vmdisk##*/}
		vm=${vm//\.img/}
		mount_single "$vm" "$vmdisk"
	done
fi
