#!/bin/bash
[[ $UID -eq 0 ]] || { echo "ERROR: this script can only be run by root (e.g. use sudo)."; exit 1; }
# LVM volume group name under which the system volumes are stored
VGNAME="KVM_GUESTS"
# Where to mount the guest disks in the file system
MNTPFX="/mnt/kvm-guests"

function umount_single
{
	local vm="$1"
	local vmdisk="$2"

	blkid|grep '"ext4"'|grep "/dev/mapper/$VGNAME-$vm.img"|cut -d : -f 1|while read vmpart; do
		if mount|grep -q "^$vmpart"; then
			echo -e "* Unmounting $vmpart"
			umount "$vmpart" || { echo -e "WARNING: failed to unmount $vmpart"; }
		fi
	done
	echo -e "\tRemoving device mappings for: $vmdisk"
	kpartx -a "$vmdisk"
}

# Banner
if (($# > 0)); then
	for vm in "$@"; do
		lvdisplay|grep 'LV Name'|grep "/dev/$VGNAME/$vm.img"|awk '{print $3}'|while read vmdisk; do
			umount_single "$vm" "$vmdisk"
		done
	done
else
	echo "Scanning for system volumes and umounting all ..."
	lvdisplay|grep 'LV Name'|grep "/dev/$VGNAME/"|grep \.img|awk '{print $3}'|while read vmdisk; do
		vm=${vmdisk##*/}
		vm=${vm//\.img/}
		umount_single "$vm" "$vmdisk"
	done
fi
