#!/bin/bash
# Works on Linux only (GNU readlink dependency)
# The script can be used to sync a repository initially created via svnsync.
# Note: the script should reside inside the local repository (not the workink copy)!
pushd `dirname $0` > /dev/null; REPO=$(readlink -nf "`pwd`"); popd > /dev/null;pushd `dirname $0` > /dev/null; CURRABSPATH=$(readlink -nf "`pwd`"); popd > /dev/null;
SVNREPO="file://$REPO"
echo "Current mirror URL ($SVNREPO): '$(svn propget svn:sync-from-url --revprop -r 0 "$SVNREPO")'"
svn propdel --revprop -r0 svn:sync-lock "$SVNREPO"
svnsync --non-interactive --trust-server-cert sync "$SVNREPO" 2>&1
hg --cwd "$REPO/hgsubversion" pull "$SVNREPO"
hg --cwd "$REPO/hgsubversion" up null
# svn switch --relocate file://$repo $SERVER$REPO
