#!/bin/bash
pushd `dirname $0` > /dev/null; CURRABSPATH=$(readlink -nf "`pwd`"); popd > /dev/null;
TGTDIR="$1"
[[ -d "$TGTDIR" ]] || exit 0
AR="$CURRABSPATH/archive"
EXT=".zip"
python2.7 "$CURRABSPATH/sysinternals-mirror"
make -f "$CURRABSPATH/GNUmakefile.sysint" -C "$AR" TARGET="$AR$EXT" && \
DATENM=$(date -r "$AR$EXT" +"$TGTDIR/%Y-%m-%dT%H-%M-%S_live.sysinternals.com$EXT") && \
	if [[ ! -e "$DATENM" ]]; then
		cp -a "$AR$EXT" "$DATENM"
	fi
date +"%Y-%m-%d %H:%M:%S"|tee "$TGTDIR/LASTUN.txt"
