#!/bin/bash
pushd `dirname $0` > /dev/null; CURRABSPATH=$(readlink -nf "`pwd`"); popd > /dev/null;
TGTDIR="$1"
[[ -d "$TGTDIR" ]] || exit 0
AR="$CURRABSPATH/archive"
EXT=".zip"
python2.7 "$CURRABSPATH/sysinternals-mirror"
make -f "$CURRABSPATH/GNUmakefile.sysint" -C "$AR" TARGET="$AR$EXT" && \
DATENM=$(date -r "$AR$EXT" +"$TGTDIR/%Y-%m-%dT%H-%M-%S_live.sysinternals.com$EXT") && \
	if [[ ! -e "$DATENM" ]]; then
		cp -a "$AR$EXT" "$DATENM"
	fi
MIRROR="$TGTDIR/mirror/"
[[ -d "$MIRROR" ]] || mkdir "$MIRROR"
if [[ -d "$MIRROR" ]]; then
	find "$AR" -type f|while read fname; do
		if [[ -f "$MIRROR/${fname##*/}" ]] && [[ ! -f "$fname" ]]; then
			rm -f "$fname"
		elif [[ "$fname" -nt "$MIRROR/${fname##*/}" ]]; then
			cp -a "$fname" "$MIRROR/${fname##*/}"
		fi
	done
	touch "$MIRROR"
fi
#date +"%Y-%m-%d %H:%M:%S"|tee "$TGTDIR/LASTRUN.txt"
