#!/usr/bin/env bash
[[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
for tool in rm rmdir dirname readlink file tempfile grep tee git date make gcc wget tar md5sum; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
( [[ -n "$DEBUG" ]] || [[ -n "$DBG" ]] ) && { DBGCONFIGURE="$SHELL -x "; set -x; }
LOCKFILE="${TMPDIR=/tmp}/${CURRABSPATH//\//_}${0##*/}.lock"
MEANDMYSELF=${0##*/}
BZIPURL="http://www.bzip.org/1.0.6/bzip2-1.0.6.tar.gz"
BZIPMD5="00b516f4704d4a7cb50a1d97e6e8e15b"
PYTHURL="https://www.python.org/ftp/python/2.7.12/Python-2.7.12.tgz"
PYTHMD5="88d61f82e3616a4be952828b3694109d"
BZIPPKG="$CURRABSPATH/${BZIPURL##*/}"
PYTHPKG="$CURRABSPATH/${PYTHURL##*/}"
TEMPDIR="$CURRABSPATH/tmp"

[[ -d "$TEMPDIR" ]] || mkdir "$TEMPDIR" || { echo "FATAL: Could not create $TEMPDIR."; exit 1; }

for i in bzip python; do
	[[ -d "$TEMPDIR/$i" ]] && rm -rf "$TEMPDIR/$i"
	[[ -d "$TEMPDIR/$i" ]] || mkdir "$TEMPDIR/$i" || { echo "FATAL: Could not create $TEMPDIR/$i."; exit 1; }
done
(
	[[ -f "$BZIPPKG" ]] || curl -o "$BZIPPKG" "$BZIPURL" || wget -qO "$BZIPPKG" "$BZIPURL" || exit 1
	[[ -f "$PYTHPKG" ]] || curl -o "$PYTHPKG" "$PYTHURL" || wget -qO "$PYTHPKG" "$PYTHURL" || exit 1
	echo "Unpacking bzip2" && tar --strip-components=1 -C "$TEMPDIR/bzip" -xvf "$BZIPPKG" && mkdir "$TEMPDIR/bzip/tempinstall"
		echo "Unpacking Python" && tar --strip-components=1 -C "$TEMPDIR/python" -xvf "$PYTHPKG" && mkdir "$TEMPDIR/python/tempinstall"
) || { echo "FATAL: Could not unpack one of the required source packages. Check above output for clues."; exit 1; }
# Configure GCC for our purpose
export CC="$TEMPDIR/musl/tempinstall/bin/musl-gcc"
export LDFLAGS="-Wl,--gc-sections"
export CFLAGS="-ffunction-sections -fdata-sections"
# proceed ...
echo "Configuring and building bzip2"
(
	cd "$TEMPDIR/bzip" && \
		make -j 8 && \
		make PREFIX="$TEMPDIR/bzip/tempinstall" install
) || { echo "FATAL: bzip2 failed to build. Check above output for clues."; exit 1; }
echo "Configuring and building Python"
(
	export LDFLAGS="-Wl,--gc-sections -static -static-libgcc"
	cd "$TEMPDIR/python" && \
		./configure --disable-shared "--prefix=$TEMPDIR/python/tempinstall" && \
		make -j 8 && \
		make install
) || { echo "FATAL: Python failed to build. Check above output for clues."; exit 1; }
#rm -rf "$TEMPDIR"
