#!/usr/bin/env bash
[[ -t 1 ]] && { cG="\e[1;32m"; cR="\e[1;31m"; cB="\e[1;34m"; cW="\e[1;37m"; cY="\e[1;33m"; cG_="\e[0;32m"; cR_="\e[0;31m"; cB_="\e[0;34m"; cW_="\e[0;37m"; cY_="\e[0;33m"; cZ="\e[0m"; export cR cG cB cY cW cR_ cG_ cB_ cY_ cW_ cZ; }
for tool in git; do type $tool > /dev/null 2>&1 || { echo -e "${cR}ERROR:${cZ} couldn't find '$tool' which is required by this script."; exit 1; }; done
pushd $(dirname $0) > /dev/null; CURRABSPATH=$(readlink -nf "$(pwd)"); popd > /dev/null; # Get the directory in which the script resides
MAINBRANCH=master
TAGNAME="${TAGNAME:-$1}"
DIRNAME=goroot
test -f "$CURRABSPATH/.${0##*/}.conf" && source "$CURRABSPATH/.${0##*/}.conf" || true
[[ -n "$TAGNAME" ]] || { echo -e "${cR}ERROR:${cZ} ${cW}TAGNAME${cZ} not set."; exit 1; }
set -e
git -C "$CURRABSPATH/$DIRNAME" clean -dfx
git -C "$CURRABSPATH/$DIRNAME" reset --hard
git -C "$CURRABSPATH/$DIRNAME" checkout $MAINBRANCH
git -C "$CURRABSPATH/$DIRNAME" pull --all
git -C "$CURRABSPATH/$DIRNAME" checkout -b "local/$TAGNAME" "$TAGNAME" || git -C "$CURRABSPATH/$DIRNAME" switch "local/$TAGNAME"
( set -x; cd "$CURRABSPATH/$DIRNAME/src" && ./all.bash ) || { echo -e "${cR}ERROR:${cZ} failed to build fresh ${cW}go${cZ}."; exit 1; }
set +e
